# /etc/systemd/system/greetd.service.d/override.conf

# Commands
# Create a configuration folder greetd.service.d
# sudo mkdir -p /etc/systemd/system/greetd.service.d
#
# Create an override.conf file to sleep for 15 seconds at boot allowing systemd to load all components before showing the display manager greeter for login
# echo -e "[Service]\nExecStartPre=/usr/bin/sleep 15" | sudo tee /etc/systemd/system/greetd.service.d/override.conf